server:
  port: ${SERVER_PORT}

base:
  path: ${BASE_URL}

spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    com.merchant: DEBUG
